#!/bin/bash
fshell=$(finger $(whoami) | sed -n 's/.*Shell: //p' | sed 1q)
SHELL=${fshell:-$SHELL}
PLAN9=${PLAN9:-/usr/local/plan9}
cd $HOME
arch=x86_64
if arch -arch arm64 date >/dev/null 2>&1; then
	arch=arm64
fi

[ -f "$HOME"/.p9p/rc ] && . "$HOME"/.p9p/rc

case "$SHELL" in
*/rc)
	echo '
		if(! ~ $PLAN9/bin $path)
			path=($path $PLAN9/bin)
		arch -arch '$arch' 9term -l -W800x800 &
	' | $SHELL -il
	exit 0
	;;
*)
	. ~/.bashrc
	;;
esac

if ! [[ :$PATH: =~ :$PLAN9/bin: ]]
then
	PATH=$PATH:$PLAN9/bin
fi
arch -arch $arch 9term -f $font -l -W800x800
exit 0
