#!/bin/bash
fshell=$(finger $(whoami) | sed -n 's/.*Shell: //p' | sed 1q)
SHELL=${fshell:-$SHELL}
PLAN9=${PLAN9:-/usr/local/plan9}
cd $HOME
[ -f $HOME/.p9p/rc ] && source $HOME/.p9p/rc

case "$SHELL" in
*/rc)
	echo '
		if(! ~ $PLAN9/bin $path)
			path=($path $PLAN9/bin)
		$PLAN9/bin/9term -l -W830x650 &
	' | $SHELL -l
	exit 0
	;;
*/bash)
	. ~/.bash_profile
	;;
*)
	. ~/.profile
	;;
esac

if ! [[ :$PATH: =~ :$PLAN9/bin: ]]
then
	PATH=$PATH:$PLAN9/bin
fi
if [ "$ARCH" = "arm64" ]; then
	arch -arm64 $PLAN9/bin/9term -l -W830x650 &
else
	$PLAN9/bin/9term -l -W830x650 &
fi
exit 0

