#!/bin/zsh -i

cd "$HOME"

if [ -f "$HOME"/.p9p/rc ]; then
	source "$HOME"/.p9p/rc
fi

if [ -x /usr/libexec/path_helper ]; then
	eval "$(/usr/libexec/path_helper -s)"
fi

PLAN9=${PLAN9:-/usr/local/plan9}

p9plumb start
tabstop=4
SHELL=rc
sam -a
