#!/usr/bin/env bash

set -e

base="$HOME"/.p9p

install_darwin()
{
	# Copy Plumb.app acme.app and 9term.app to /Applications
	for i in "$PLAN9"/mac/Plumb.app "$PLAN9"/mac/9term.app $base/mac/Acme.app $base/mac/Sam.app; do
		if [ ! -d /Applications/"$(basename "$i")" ]; then
			echo "Installing $i in /Applications/$(basename "$i")"
			cp -r "$i" /Applications/
		else
			echo "/Applications/$(basename "$i") already exists.. skipping"
		fi
	done
}

if [ ! -d "$base" ]; then
	echo "$base not found or doesn't exist, please set \$base in $0 to the correct path"
	exit 2
fi

if [ "$(uname -s)" = "Darwin" ]; then
	install_darwin
fi

# Install devdrawserver
[ ! -d "$base"/cmd/devdrawserver ] && {
	cd "$base"/cmd/
	git clone https://github.com/mariusae/devdrawserver.git
} 

[ ! -x "$PLAN9"/bin/devdrawserver ] && {
	cd "$base"/cmd/devdrawserver && git pull && mk install && mk clean
}|| echo "devdrawserver is already installed in: $PLAN9/bin/devdrawserver"

[ ! -x "$base"/bin/acmedot ] && {
	cd "$base"/cmd/acmedot
	go build && mv acmedot "$base"/bin/
} || echo "acmedot already installed in: $base/bin/acmedot"

cd "$base"
