#!/bin/bash

set -e
base=$HOME/.p9p

install_darwin()
{
	# Copy Plumb.app acme.app and 9term.app to /Applications
	for i in $PLAN9/mac/Plumb.app $PLAN9/mac/9term.app $base/bin/Acme.app $base/bin/Sam.app; do
		if [ ! -d /Applications/$(basename $i) ]; then
			echo "Installing $i in /Applications/$(basename $i)"
			cp -r $i /Applications
		else
			echo "/Applications/$(basename $i) already exists.. skipping"
		fi
	done
}

if [ ! -d $base ]; then
	echo "$base not found or doesn't exist, please set \$base in $0 to the correct path"
	exit 2
fi

if [ $(uname -s) = Darwin ]; then
	install_darwin
fi

# Get devdrawserver and gitfiles
[ -d $base/cmd/tab ] && {
	cd $base/cmd/tab && mk install && mk clean
}

[ ! -d $base/cmd/devdrawserver ] && {
	cd $base/cmd/
	git clone ssh://git@github.com/mariusae/devdrawserver.git
}
cd $base/cmd/devdrawserver && mk install && mk clean

[ ! -d $base/cmd/gitfiles ] && {
	cd $base/cmd/
	git clone ssh://git@github.com/mariusae/gitfiles.git
}
cd $base/cmd/gitfiles && mk install && mk clean
cd $base
