#!/bin/bash

[ -d /usr/local/plan9 ] && export PLAN9=${PLAN9:-/usr/local/plan9}

# Let gs find the plan9port document fonts.
GS_FONTPATH=$PLAN9/postscript/font
BROWSER=safari

# Prompt (is almost a no-op in bash)
H=$(hostname | sed 's/\..*//')

# Equivalent variables for rc(1).
home=$HOME
prompt="% 	"
user=$USER
EDITOR=/usr/local/plan9/bin/B
GIT_EDITOR=$(command -v E)
#font=/lib/font/bit/lucsans/euro.8.font
#fixedfont=/lib/font/bit/lucm/unicode.9.font
font=/mnt/font/LucidaGrande/14a/font,/mnt/font/LucidaGrande/28a/font
fontfixed=/mnt/font/LucidaGrandeMono/13a/font,/mnt/font/LucidaGrandeMono/26a/font
NAMESPACE=/tmp/ns.$H
export home prompt user font fontfixed GS_FONTPATH BROWSER H EDITOR GIT_EDITOR NAMESPACE

# if $NAMESPACE doesn't exist, we need to create it.
[ -d "$NAMESPACE" ] || mkdir "$NAMESPACE"

if [ "$TERM" = dumb ]; then
	_cd(){
		\cd "$@" &&
		case "TERM!$-" in
		linux!*)
			;;
		 *!*i*)
			awd
		 esac
	}
	alias cd=_cd
	alias cls=cw
	set +o emacs
	set +o vi
	set -a # autoexport
	unset PROMPT_COMMAND
	# Plumb files instead of starting new editor.
	unset FCEDIT VISUAL
	# Make sure mpage prints in letter mode.
	MPAGE="-t -bLetter"
	# Get rid of backspace characters in Unix man output.
	PAGER=nobs
	IPY_TEST_SIMPLE_PROMPT=1
	export MPAGE PAGER IPY_TEST_SIMPLE_PROMPT

	if [ -x /usr/local/bin/brew ]; then
		HOMEBREW_NO_EMOJI=1
		HOMEBREW_INSTALL_BADGE=''
		export HOMEBREW_NO_EMOJI HOMEBREW_INSTALL_BADGE
		_br(){
			cmd="$1";shift
			brew "$cmd" "$@"|nobs
		}
		alias brew=_br
	fi
fi

# aliases
alias get_plan9="git clone git@github.com:xmonk/plan9port.git $HOME/t/plan9"
alias lf="$PLAN9/bin/lc -F"

# functions
bld_plan9() {
	wd=$(pwd)
	cd "$PLAN9" || return
	./INSTALL
	cd "$wd" || return
	unset wd
}

# start your engines.
[ -x "$HOME"/.p9p/bin/p9plumb ] && "$HOME"/.p9p/bin/p9plumb start
