#!/bin/sh

[ -d /usr/local/plan9 ] && export PLAN9=${PLAN9:-/usr/local/plan9}

# Let gs find the plan9port document fonts.
export GS_FONTPATH=$PLAN9/postscript/font
export BROWSER=google-chrome
# Prompt (is almost a no-op in bash)
export H=`hostname | sed 's/\..*//'`

# Equivalent variables for rc(1).
export home=$HOME
export prompt=";; 	"
export user=$USER
export EDITOR=/usr/local/plan9/bin/E
#export font=/lib/font/bit/lucsans/euro.8.font
#export fixedfont=/lib/font/bit/lucm/unicode.9.font
export font=/mnt/font/LucidaGrandeMono/13a/font,/mnt/font/LucidaGrandeMono/26a/font
export fixedfont=/mnt/font/LucidaGrande/13a/font,/mnt/font/LucidaGrande/26a/font
export NAMESPACE=/tmp/ns.$(hostname -s)
# if $NAMESPACE doesn't exist, we need to create it.
[ -d $NAMESPACE ] ||  mkdir $NAMESPACE

if [ $TERM = dumb ]; then
	_cd(){
		\cd "$@" &&
		case "TERM!$-" in
		linux!*)
			;;
		 *!*i*)
			awd
		 esac
	}
	alias cd=_cd
	set +o emacs
	set +o vi
	set -a # autoexport
	unset PROMPT_COMMAND
	# Plumb files instead of starting new editor.
	unset FCEDIT VISUAL
	# Make sure mpage prints in letter mode.
	export MPAGE="-t -bLetter"
	# Get rid of backspace characters in Unix man output.
	export PAGER=nobs
	export IPY_TEST_SIMPLE_PROMPT=1
fi

# start your engines.
[ -x $HOME/.p9p/bin/p9plumb ] && $HOME/.p9p/bin/p9plumb start
