#!/bin/bash

arch=x86_64
if arch -arch arm64 date >/dev/null 2>&1; then
        arch=arm64
fi

cd "$HOME" || exit 1

if [ -f "$HOME"/.p9p/rc ]; then
	source "$HOME"/.p9p/rc
fi


PLAN9=${PLAN9:-/usr/local/plan9}

if [ -x /usr/libexec/path_helper ]; then
	eval "$(/usr/libexec/path_helper -s)"
fi

p9plumb start

tabstop=4
args=("-a")

if [ -f "$HOME"/acme.dump ]; then
	args+=("-l" "$HOME/acme.dump")
else
	[ -n "$font" ] && args+=("-f" "$font")
	[ -n "$fixedfont" ] && args+=("-F" "$fixedfont")
fi

arch -arch $arch $PLAN9/bin/acme "${args[@]}"
unset args arch
